/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction'
    },
    {
      type: 'category',
      label: 'Module 1 – Foundations & Infrastructure',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '00-setup',
        },
        {
          type: 'autogenerated',
          dirName: '01-foundations',
        },
        {
          type: 'autogenerated',
          dirName: '02-ros2',
        },
        {
          type: 'autogenerated',
          dirName: '03-modeling',
        }
      ],
    },
    {
      type: 'category',
      label: 'Module 2 – Simulation & Perception',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '04-simulation',
        },
        {
          type: 'autogenerated',
          dirName: '05-perception',
        }
      ],
    },
    {
      type: 'category',
      label: 'Module 3 – Locomotion & Dexterous Manipulation',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '06-locomotion',
        },
        {
          type: 'autogenerated',
          dirName: '07-manipulation',
        }
      ],
    },
    {
      type: 'category',
      label: 'Module 4 – Intelligence, Transfer & Responsibility',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '08-vla',
        },
        {
          type: 'autogenerated',
          dirName: '09-sim2real',
        },
        {
          type: 'autogenerated',
          dirName: '10-safety-ethics',
        },
        {
          type: 'autogenerated',
          dirName: '11-capstone',
        }
      ],
    }
  ],
};

module.exports = sidebars;